/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedFollowingRouteImport } from './routes/_authenticated.following'
import { Route as AiHandleRouteImport } from './routes/ai.$handle'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated.account.index'
import { Route as AuthenticatedAccountContentMaturityRouteImport } from './routes/_authenticated.account.content-maturity'
import { Route as AuthenticatedAccountInfoRouteImport } from './routes/_authenticated.account.info'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated.account.notifications'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminAgentsIndexRouteImport } from './routes/_authenticated.admin.agents.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFollowingRoute = AuthenticatedFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AiHandleRoute = AiHandleRouteImport.update({
  id: '/ai/$handle',
  path: '/ai/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountContentMaturityRoute =
  AuthenticatedAccountContentMaturityRouteImport.update({
    id: '/account/content-maturity',
    path: '/account/content-maturity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountInfoRoute =
  AuthenticatedAccountInfoRouteImport.update({
    id: '/account/info',
    path: '/account/info',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAgentsIndexRoute =
  AuthenticatedAdminAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/following': typeof AuthenticatedFollowingRoute
  '/ai/$handle': typeof AiHandleRoute
  '/post/$id': typeof PostIdRoute
  '/account/content-maturity': typeof AuthenticatedAccountContentMaturityRoute
  '/account/info': typeof AuthenticatedAccountInfoRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/agents/': typeof AuthenticatedAdminAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/following': typeof AuthenticatedFollowingRoute
  '/ai/$handle': typeof AiHandleRoute
  '/post/$id': typeof PostIdRoute
  '/account/content-maturity': typeof AuthenticatedAccountContentMaturityRoute
  '/account/info': typeof AuthenticatedAccountInfoRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/following': typeof AuthenticatedFollowingRoute
  '/ai/$handle': typeof AiHandleRoute
  '/post/$id': typeof PostIdRoute
  '/_authenticated/account/content-maturity': typeof AuthenticatedAccountContentMaturityRoute
  '/_authenticated/account/info': typeof AuthenticatedAccountInfoRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/agents/': typeof AuthenticatedAdminAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/following'
    | '/ai/$handle'
    | '/post/$id'
    | '/account/content-maturity'
    | '/account/info'
    | '/account/notifications'
    | '/account/'
    | '/admin/'
    | '/admin/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/following'
    | '/ai/$handle'
    | '/post/$id'
    | '/account/content-maturity'
    | '/account/info'
    | '/account/notifications'
    | '/account'
    | '/admin'
    | '/admin/agents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/following'
    | '/ai/$handle'
    | '/post/$id'
    | '/_authenticated/account/content-maturity'
    | '/_authenticated/account/info'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  AiHandleRoute: typeof AiHandleRoute
  PostIdRoute: typeof PostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/following': {
      id: '/_authenticated/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof AuthenticatedFollowingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/ai/$handle': {
      id: '/ai/$handle'
      path: '/ai/$handle'
      fullPath: '/ai/$handle'
      preLoaderRoute: typeof AiHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/content-maturity': {
      id: '/_authenticated/account/content-maturity'
      path: '/account/content-maturity'
      fullPath: '/account/content-maturity'
      preLoaderRoute: typeof AuthenticatedAccountContentMaturityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/info': {
      id: '/_authenticated/account/info'
      path: '/account/info'
      fullPath: '/account/info'
      preLoaderRoute: typeof AuthenticatedAccountInfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agents/': {
      id: '/_authenticated/admin/agents/'
      path: '/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AuthenticatedAdminAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAgentsIndexRoute: typeof AuthenticatedAdminAgentsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAgentsIndexRoute: AuthenticatedAdminAgentsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFollowingRoute: typeof AuthenticatedFollowingRoute
  AuthenticatedAccountContentMaturityRoute: typeof AuthenticatedAccountContentMaturityRoute
  AuthenticatedAccountInfoRoute: typeof AuthenticatedAccountInfoRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFollowingRoute: AuthenticatedFollowingRoute,
  AuthenticatedAccountContentMaturityRoute:
    AuthenticatedAccountContentMaturityRoute,
  AuthenticatedAccountInfoRoute: AuthenticatedAccountInfoRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  AiHandleRoute: AiHandleRoute,
  PostIdRoute: PostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
